version: "3.7"

services:
  webapp:
    image: maissae/modern-physics:latest
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "3306"
    network_mode: "bridge"
    volumes:
      - type: bind
        source: /home/maissae/container
        target: /app/content
    deploy:
      replicas: 1
    environment:
      SqlConnectionString: "Server=172.17.0.4;Database=AppDb;Uid=root;Pwd=P@ssw0rd;"
      AdminUsername: "admin"
      AdminPassword: "P@ssw0rd"