version: "3.7"

services:
  webapp:
    image: maissae/modern-physics:latest
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "3306"
    network_mode: "bridge"
    volumes:
      - type: bind
        source: {ServerPath}
        target: /app/content
    deploy:
      replicas: 1
    environment:
      SqlConnectionString: "{ConnectionString}"
      AdminUsername: "{Username}"
      AdminPassword: "{Password}"
      GoogleAnalyticsTrackingId : "{UA-XXXXX-Y}"